### ISSUE TITLE
Add release tag

### ISSUE THREAD

**Issue by andybest** [PureSwift/SDL#1]
Hi,

Would it be possible to add a release tag to the repo, as it can't currently be imported as a dependency without one.

Thanks

**Comment by colemancda** [comment]
I made a `1.0.0` tag, but its not necessary in Swift 4, see [PureSwift/Cacao](https://github.com/PureSwift/Cacao/blob/master/Package.swift)

**Comment by andybest** [comment]
It seems like there is a problem with using a package that depends on a package which uses a branch https://bugs.swift.org/browse/SR-5000. I ran into this error today, but hopefully these fixes to SPM will make it into the next XCode 9.0 beta release
