### ISSUE TITLE
swift run: error 'Int' has no member 'rawValue'

### ISSUE THREAD

**Issue by UnGast** [PureSwift/SDL#9]
Thanks for the library. I'm totally new to this and your lib is the first I got working.

After #8, when running `swift run` I get errors of this kind:

`error: value of type 'Int' has no member 'rawValue'
    static let argb8888 = SDLPixelFormat.Format(rawValue: UInt32(SDL_PIXELFORMAT_ARGB8888.rawValue))`

So I went to back to a version before this pull was merged and it worked.

MacOS 10.15.1
Apple Swift version 5.1.3 (swiftlang-1100.0.282.1 clang-1100.0.33.15)
Target: x86_64-apple-darwin19.0.0

**Comment by thara** [comment]
@UnGast Which SDL2 version do you use?
My build is successful with SDL2 2.0.10, the latest version on Homebrew.

SDL_PIXELFORMAT was anonymous enum and we has been able to use them as Int from Swift.
However, [This issue](https://bugzilla.libsdl.org/show_bug.cgi?id=4377) on SDL2 was fixed, so SDL_PIXELFORMAT became *named* enum and we was able to use SDL_PIXELFORMAT enum from Swift now.

**Comment by UnGast** [comment]
@thara My setup changed, I don't have access to MacOS right now so I can't check but as far as I remember I used the latest version from Homebrew as well. Now I'm on Ubuntu 19.10 and everything works fine.

**Comment by thara** [comment]
@UnGast There are differences in SDL2 versions published by different package managers or platforms.
All of package managers do not always follow new versions immediately, even if SDL2 published new versions itself.
Check the actual version of SDL2 by `brew info sdl2`.
If it needed, try to update SDL2 by `brew update && brew upgrade sdl2` .
